### ISSUE TITLE
Bot does not reply to tweets that contain more than one image

### ISSUE THREAD

**Issue by GrygrFlzr** [petzku/taiga-fix-twitter#3]
#2 partially addresses this by supporting multi-image Sensitive Tweets as the images are never included by the native embed, but ironically this leaves SFW tweets hanging.
There's no good way to detect the number of images directly from the embed, so the most likely solution is to do an additional request to the FxTwitter API and checking that `tweet.media.mosaic` exists.
In case it is beyond the scope of the project to rely on FxTwitter for basic functionality, I'm opening an issue first instead of submitting a PR for this.

**Comment by petzku** [comment]
This seems like reasonable behavior to implement. I don't _love_ relying on specifically fxtwitter, but it seems like a good approach. Feel free to PR.

**Comment by petzku** [comment]
Addressed in #4.
